import { sequelize } from '../config/db.js';
import { DataTypes } from 'sequelize';

const users = sequelize.define('users', {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    userName: {
        type: DataTypes.STRING(255),
        allowNull: false,
        unique: true,
    },
    name: {
        type: DataTypes.STRING(255),
        allowNull: false,
        defaultValue: '',
        unique: true,
    },
    password: {
        type: DataTypes.STRING(255),
        allowNull: false,
    },
    color: {
        type: DataTypes.STRING(255),
        allowNull: false,
        unique: true,
    },
    externalID: {
        type: DataTypes.STRING(255),
        allowNull: true,
        unique: true,
    },
    img: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    role: {
        type: DataTypes.ENUM('admin', 'employee', 'infordio'),
        allowNull: false,
    },
    permission_group: {
        type: DataTypes.INTEGER,
        allowNull: true,
        defaultValue: 1,
    },
    discontinued:                           { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    dashboard_module:                       { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    rooms_module:                           { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    rooms_crud_module:                      { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    users_module:                           { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    users_crud_module:                      { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    users_breaks_module:                    { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    users_breaks_crud_module:               { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    waitinglists_module:                    { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    waitinglists_crud_module:               { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    crm_module:                             { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    crm_crud_module:                        { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    groups_module:                          { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    groups_crud_module:                     { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    typeevents_module:                      { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    typeevents_crud_module:                 { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    plans_module:                           { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    plans_crud_module:                      { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    regulations_module:                     { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    regulations_crud_module:                { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    articles_invoiced_module:               { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    articles_not_invoiced_module:           { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    clients_articles_invoiced_module:       { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    clients_articles_not_invoiced_module:   { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    logs_invoiced_module:                   { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    logs_receipt_module:                    { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    clients_module:                         { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    clients_crud_module:                    { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    covenants_module:                       { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    covenants_crud_module:                  { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    cycles_covenants_module:                { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    cycles_covenants_crud_module:           { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    attachments_module:                     { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    attachments_crud_module:                { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    observations_module:                    { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    observations_crud_module:               { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    prices_change_module:                   { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    prices_change_crud_module:              { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    import_clients_erp_module:              { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    see_everyones_appointments_module:      { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    create_everyones_appointments_module:   { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    import_artigos_erp_module:              { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    blue_document_bag:                      { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    settings_edit:                          { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    especialidade: {
        type: DataTypes.INTEGER,
        allowNull: true,
    },
}, {
    tableName: 'users',
    timestamps: true,
});

export default users;